// test/pop-quests-sync.test.js — apps/mimic/pop-quests.js is GENERATED from the website's PoP guide
// (web/lib/popGuide.ts + popGuideMore.ts) by scripts/sync-pop-quests.js, because the site must not
// import from outside web/ and Mimic must not import from the site. This is the drift gate, same idea
// as check:dashboard: edit the web files, forget the sync, and the Quests mode of the PoP overlay
// quietly serves yesterday's guide.
//
// The guild lead, 2026-10-03: "the pop overlay should include the quests and a mode for selecting them
// and all of the things to say or do for any of the pop quests or flags so we can reference them."
//
// Run: npx vitest run test/pop-quests-sync.test.js
// Fix a red one with: npm run sync:pop-quests

import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import { createRequire } from 'node:module';
import { ROOT } from './_source-slice.js';
import { GUIDE_ITEMS, GUIDE_SECTIONS, ZONE_NAMES } from '../web/lib/popGuide.ts';
import { GUIDE_LEVELS } from '../web/lib/popGuideMore.ts';

const sync = createRequire(import.meta.url)(path.join(ROOT, 'scripts', 'sync-pop-quests.js'));
// (CRLF-tolerant: a Windows checkout with autocrlf must not read as drift.)
const generated = fs.readFileSync(sync.OUT, 'utf8').replace(/\r\n/g, '\n');
const load = () => { const w = {}; vm.runInNewContext(generated, { window: w }); return w.POP_QUESTS; };
const quests = (d) => d.levels.flatMap(lv => lv.sections.flatMap(s => s.quests));

describe('pop-quests.js is the generated copy of the web guide', () => {
  it('is exactly what the generator writes now (a red here means: npm run sync:pop-quests)', async () => {
    const want = await sync.buildSource();
    // Not expect(a).toBe(b): a 50 KB string diff buries the one line that matters.
    expect(generated === want, 'apps/mimic/pop-quests.js is stale: run npm run sync:pop-quests').toBe(true);
  });

  it('carries its do-not-edit banner, and loads as plain data in a bare context', () => {
    expect(generated).toMatch(/GENERATED by scripts\/sync-pop-quests\.js[\s\S]{0,200}do not edit/);
    const d = load();
    expect(Array.isArray(d.levels)).toBe(true);
    // ES5-safe: nothing but JSON after the assignment (no arrows, template strings, let/const).
    const body = generated.slice(generated.indexOf('window.POP_QUESTS = ') + 'window.POP_QUESTS = '.length).replace(/;\s*$/, '');
    expect(JSON.parse(body)).toEqual(d);
  });

  it('has every web guide step, once, in guide order, grouped by the same levels and sections', () => {
    const d = load();
    const flat = quests(d).map(q => q.key);
    const web = GUIDE_SECTIONS.flatMap(s => GUIDE_ITEMS.filter(i => i.section === s.key).map(i => i.key));
    expect(flat).toEqual(GUIDE_LEVELS.flatMap(lv => lv.sections.flatMap(sk => GUIDE_ITEMS.filter(i => i.section === sk).map(i => i.key))));
    expect([...flat].sort()).toEqual([...web].sort());
    expect(d.levels.map(l => l.key)).toEqual(GUIDE_LEVELS.map(l => l.key));
    expect(d.levels.map(l => l.sections.map(s => s.key))).toEqual(GUIDE_LEVELS.map(l => l.sections));
  });

  it('carries the guide\'s words, places and hand-ins untouched: nothing is added on the way', () => {
    const byKey = new Map(quests(load()).map(q => [q.key, q]));
    for (const i of GUIDE_ITEMS) {
      const q = byKey.get(i.key);
      expect(q.who, i.key).toBe(i.who);
      expect((q.says || []).map(s => [s.to, s.text, !!s.sit]), i.key).toEqual((i.says || []).map(s => [s.to, s.text, !!s.sit]));
      expect((q.where || []).map(l => [l.npc, l.zone, l.y, l.x]), i.key).toEqual((i.where || []).map(l => [l.npc, ZONE_NAMES[l.zone], l.y, l.x]));
      if (i.chain) {
        expect(q.chain.first.say, i.key).toEqual(i.chain.first.say);
        expect(q.chain.talk.map(s => s.say), i.key).toEqual(i.chain.talk.map(s => s.say));
        expect(q.chain.handins.length, i.key).toBe(i.chain.handins.length);
      } else {
        expect(q.chain, i.key).toBeUndefined();
      }
    }
  });

  it('carries every step’s seq (the guild lead, 2026-10-03: one ordered list per step) act for act, in order, with its script', () => {
    const byKey = new Map(quests(load()).map(q => [q.key, q]));
    const fields = ['kind', 'to', 'text', 'sit', 'times', 'until', 'src'];
    let n = 0;
    for (const i of GUIDE_ITEMS) {
      const q = byKey.get(i.key);
      if (!i.seq) { expect(q.seq, i.key).toBeUndefined(); continue; }
      expect(q.seq.length, i.key).toBe(i.seq.length);
      i.seq.forEach((a, k) => {
        for (const f of fields) expect(q.seq[k][f], `${i.key}[${k}].${f}`).toEqual(a[f]);
        // Item tokens come through as the bare name, one per token and in the same order.
        expect(q.seq[k].items, `${i.key}[${k}].items`).toEqual(a.items?.map(t => t.replace(/\[\[([^\]#]+)#\d+\]\]/g, '$1')));
        n++;
      });
    }
    expect(n).toBeGreaterThan(300);
    // The model case reads in full: "continue" twice, then the shrine.
    const askr = byKey.get('flag_askr').seq;
    expect(askr.find(a => a.text === 'continue').times).toBe(2);
    expect(askr[askr.length - 1]).toMatchObject({ kind: 'zone', src: 'postorms/player.lua' });
    expect(askr[0].items).toEqual(['Storm Giant Head']);
    expect(byKey.get('start_flag_fixers').seq.find(a => a.until)).toMatchObject({ text: 'unlock my memories', sit: true });
  });

  it('turns [[Item#id]] tokens into the bare item name, everywhere', () => {
    expect(generated).not.toMatch(/\[\[|#\d+\]\]/);
    const q = quests(load()).find(x => x.key === 'pok_taxidermy');
    expect(q.title).toBe('Collection of Taxidermy → Fine Antique Ring');
    expect(q.detail).toContain('combine Tiny Rockhopper Eye, Undead Froglok Tongue');
    const handin = quests(load()).find(x => x.key === 'start_traveler_manual').chain.handins[0];
    expect(handin.give).toBe('History of Evils: The Age of Scale');
    expect(handin.get).toBe('Note to Caden');
  });

  it('keeps the /sit marker and the expect / turn-in / go-back notes the beta layouts add', () => {
    const byKey = new Map(quests(load()).map(q => [q.key, q]));
    expect(byKey.get('start_flag_fixers').says.filter(s => s.sit).map(s => s.text)).toEqual(['guided meditation', 'unlock my memories']);
    expect(byKey.get('flag_askr').turnIn.length).toBeGreaterThan(0);
    expect(byKey.get('flag_askr').expect).toBeTruthy();
    expect(byKey.get('justice_mavuin_info').back[0].npc).toBe('The Tribunal');
  });
});
