// pop-quests.js — the PoP guide's quests and flags, for the Quests mode of the PoP overlay
// (popraid.html loads this via <script src>).
//
// GENERATED by scripts/sync-pop-quests.js from web/lib/popGuide.ts + popGuideMore.ts — do not edit
// by hand. Change the web files, then run `npm run sync:pop-quests`. test/pop-quests-sync.test.js
// fails when this file is stale. Every phrase and place in here was checked against the NPC's
// quest script and spawn table when it went into the web guide; nothing is added on the way.
window.POP_QUESTS = {
 "levels": [
  {
   "key": "before",
   "title": "Before the planes",
   "sub": "Start here · Knowledge quests · your spells",
   "color": "#6e7681",
   "sections": [
    {
     "key": "start",
     "title": "Start here",
     "blurb": "Do these first. Most take a minute.",
     "quests": [
      {
       "key": "start_level46",
       "title": "Reach level 46",
       "who": "solo",
       "must": true,
       "detail": "Every PoP zone needs 46. The Plane of Knowledge does not; the Plane of Time asks for more."
      },
      {
       "key": "start_pok_bind",
       "title": "Get to the Plane of Knowledge and bind there",
       "who": "solo",
       "detail": "Its books reach most of Norrath, so it becomes your home for the expansion.",
       "says": [
        {
         "to": "Soulbinder Jera",
         "text": "bind my soul"
        }
       ],
       "where": [
        {
         "npc": "Soulbinder Jera",
         "zone": "Plane of Knowledge",
         "y": -221,
         "x": -53
        }
       ]
      },
      {
       "key": "start_popflags",
       "title": "Type #popflags in game",
       "who": "solo",
       "must": true,
       "detail": "New server command: lists your PoP flags by tier. Add overview, 1 to 5, time or all."
      },
      {
       "key": "start_mimic",
       "title": "Run Mimic while you play",
       "who": "solo",
       "detail": "Every flag you earn is recorded for you and ticks the matching box on this page."
      },
      {
       "key": "start_guild_books",
       "title": "Find the guild-instance books in the Plane of Tranquility",
       "who": "solo",
       "must": true,
       "detail": "PoP raids now run in guild instances. You must be in the guild or the raid to use the books."
      },
      {
       "key": "start_hails",
       "title": "The two rules that break flags",
       "who": "solo",
       "must": true,
       "detail": "Talk to the right NPC before AND after each boss; after a kill, hail A Planar Projection. And the first time you earn a flag, zone into the next plane from the one you are in (Valor → Halls of Honor, Storms → Bastion of Thunder)."
      },
      {
       "key": "start_flag_fixers",
       "title": "Meet the two flag fixers in PoK",
       "who": "solo",
       "must": true,
       "detail": "Seer Mal Nae`Shi shows and repairs your flags, but only while you sit: /sit, then say her line. If she answers that “no recent events spark a memory”, there is nothing new to unlock yet. Grand Librarian Maelin hands out the flags you are owed. Repeat each phrase until nothing new comes. Visit Maelin before and after the Zeks and after Saryrn.",
       "says": [
        {
         "to": "Seer Mal Nae`Shi",
         "text": "guided meditation",
         "sit": true
        },
        {
         "to": "Seer Mal Nae`Shi",
         "text": "unlock my memories",
         "sit": true
        },
        {
         "to": "Grand Librarian Maelin",
         "text": "Hail"
        },
        {
         "to": "Grand Librarian Maelin",
         "text": "what lore"
        },
        {
         "to": "Grand Librarian Maelin",
         "text": "what information"
        }
       ],
       "where": [
        {
         "npc": "Seer Mal Nae`Shi",
         "zone": "Plane of Knowledge",
         "y": -42,
         "x": -224,
         "note": "next to the Plane of Tranquility book"
        },
        {
         "npc": "Grand Librarian Maelin",
         "zone": "Plane of Knowledge",
         "y": 6,
         "x": 1016,
         "note": "top of the library elevator"
        }
       ]
      },
      {
       "key": "start_charm",
       "title": "Pick up your charm, the Intricate Wooden Figurine",
       "who": "solo",
       "must": true,
       "check": true,
       "detail": "Gram Dunnar gives it free. Come back each time you open a new zone for free AA and charm upgrades.",
       "says": [
        {
         "to": "Gram Dunnar",
         "text": "craft"
        },
        {
         "to": "Gram Dunnar",
         "text": "I have stories"
        }
       ],
       "where": [
        {
         "npc": "Gram Dunnar",
         "zone": "Plane of Knowledge",
         "y": -341,
         "x": -181
        }
       ]
      },
      {
       "key": "start_traveler_manual",
       "title": "Planar Traveler’s Manual (Willamina’s Needles)",
       "who": "solo",
       "must": true,
       "detail": "All inside PoK, no fighting. Start at Agrakath Theric and fetch him one book; ten hand-ins later, Willamina gives you the manual. Needed for the Beginner Manual quests later.",
       "chain": {
        "first": {
         "text": "Start at Agrakath Theric. He wants History of Evils: The Age of Scale, which lies on the floor on the upper level of Myrist: one is up at a time, back 30 minutes after someone takes it. Hand it to him and walk the hand-ins below; no NPC needs the talk before taking its item.",
         "at": {
          "npc": "Agrakath Theric",
          "zone": "Plane of Knowledge",
          "y": -554,
          "x": 1219
         },
         "say": [
          "erase the debt"
         ],
         "fetch": {
          "npc": "History of Evils: The Age of Scale",
          "zone": "Plane of Knowledge",
          "y": -94,
          "x": 973,
          "note": "on the floor, upper level of Myrist"
         }
        },
        "talk": [
         {
          "at": {
           "npc": "Willamina",
           "zone": "Plane of Knowledge",
           "y": -427,
           "x": 1154
          },
          "say": [
           "quests",
           "help"
          ],
          "note": "Her needles are late. Bolcen Tendag was bringing them."
         },
         {
          "at": {
           "npc": "Bolcen Tendag",
           "zone": "Plane of Knowledge",
           "y": 685,
           "x": 954
          },
          "say": [
           "needles"
          ],
          "note": "He is too ill to go. Mirao Frostpouch has an elixir."
         },
         {
          "at": {
           "npc": "Mirao Frostpouch",
           "zone": "Plane of Knowledge",
           "y": -88,
           "x": -215
          },
          "say": [
           "I have come for the elixir"
          ],
          "note": "Out of medicine: he needs black lava powder, and Cador has some."
         },
         {
          "at": {
           "npc": "Oracle Cador",
           "zone": "Plane of Knowledge",
           "y": 696,
           "x": 102
          },
          "say": [
           "black lava powder"
          ],
          "note": "Only for an artifact that Onirelin Gali holds."
         },
         {
          "at": {
           "npc": "Onirelin Gali",
           "zone": "Plane of Knowledge",
           "y": -650,
           "x": 1053
          },
          "say": [
           "artifact"
          ],
          "note": "Only for his jewel back. Arch Mage Narik took it."
         },
         {
          "at": {
           "npc": "Arch Mage Narik",
           "zone": "Plane of Knowledge",
           "y": 428,
           "x": 20
          },
          "say": [
           "jewel"
          ],
          "note": "Only for his engagement ring. Elisha Dirtyshoes has it."
         },
         {
          "at": {
           "npc": "Elisha Dirtyshoes",
           "zone": "Plane of Knowledge",
           "y": 394,
           "x": 945
          },
          "say": [
           "ring"
          ],
          "note": "Only if Boiron Ston likes her."
         },
         {
          "at": {
           "npc": "Boiron Ston",
           "zone": "Plane of Knowledge",
           "y": 30,
           "x": 323
          },
          "say": [
           "Do you like Elisha Dirtyshoes"
          ],
          "note": "His family standard is gone. Caden Zharik stole it."
         },
         {
          "at": {
           "npc": "Caden Zharik",
           "zone": "Plane of Knowledge",
           "y": -342,
           "x": 752
          },
          "say": [
           "standard"
          ],
          "note": "He stole it to pay Agrakath Theric."
         },
         {
          "at": {
           "npc": "Agrakath Theric",
           "zone": "Plane of Knowledge",
           "y": -554,
           "x": 1219
          },
          "say": [
           "erase the debt"
          ],
          "note": "He will clear the debt for the book in Myrist."
         }
        ],
        "handins": [
         {
          "at": {
           "npc": "Agrakath Theric",
           "zone": "Plane of Knowledge",
           "y": -554,
           "x": 1219
          },
          "give": "History of Evils: The Age of Scale",
          "get": "Note to Caden"
         },
         {
          "at": {
           "npc": "Caden Zharik",
           "zone": "Plane of Knowledge",
           "y": -342,
           "x": 752
          },
          "give": "Note to Caden",
          "get": "Boiron’s Standard"
         },
         {
          "at": {
           "npc": "Boiron Ston",
           "zone": "Plane of Knowledge",
           "y": 30,
           "x": 323
          },
          "give": "Boiron’s Standard",
          "get": "Letter to Elisha"
         },
         {
          "at": {
           "npc": "Elisha Dirtyshoes",
           "zone": "Plane of Knowledge",
           "y": 394,
           "x": 945
          },
          "give": "Letter to Elisha",
          "get": "Narik’s Ring"
         },
         {
          "at": {
           "npc": "Arch Mage Narik",
           "zone": "Plane of Knowledge",
           "y": 428,
           "x": 20
          },
          "give": "Narik’s Ring",
          "get": "Onirelin’s Jewel"
         },
         {
          "at": {
           "npc": "Onirelin Gali",
           "zone": "Plane of Knowledge",
           "y": -650,
           "x": 1053
          },
          "give": "Onirelin’s Jewel",
          "get": "Cador’s Artifact"
         },
         {
          "at": {
           "npc": "Oracle Cador",
           "zone": "Plane of Knowledge",
           "y": 696,
           "x": 102
          },
          "give": "Cador’s Artifact",
          "get": "Black Lava Powder"
         },
         {
          "at": {
           "npc": "Mirao Frostpouch",
           "zone": "Plane of Knowledge",
           "y": -88,
           "x": -215
          },
          "give": "Black Lava Powder",
          "get": "Curative Potion"
         },
         {
          "at": {
           "npc": "Bolcen Tendag",
           "zone": "Plane of Knowledge",
           "y": 685,
           "x": 954
          },
          "give": "Curative Potion",
          "get": "New Sewing Needles"
         },
         {
          "at": {
           "npc": "Willamina",
           "zone": "Plane of Knowledge",
           "y": -427,
           "x": 1154
          },
          "give": "New Sewing Needles",
          "get": "Planar Traveler’s Manual"
         }
        ]
       }
      }
     ]
    },
    {
     "key": "pok",
     "title": "Plane of Knowledge quests",
     "blurb": "Open now, ordered easy to hard. Small rewards; good for alts.",
     "quests": [
      {
       "key": "pok_taxidermy",
       "title": "Collection of Taxidermy → Fine Antique Ring",
       "who": "solo",
       "detail": "Get a Collector’s Box from Curator Merri, combine Tiny Rockhopper Eye, Undead Froglok Tongue, Cockatrice Beak and High Quality Cougarskin in it, and hand it to Holly Longtail.",
       "says": [
        {
         "to": "Curator Merri",
         "text": "collector's box"
        }
       ],
       "where": [
        {
         "npc": "Curator Merri",
         "zone": "Plane of Knowledge",
         "y": 865,
         "x": 668
        },
        {
         "npc": "Holly Longtail",
         "zone": "Plane of Knowledge",
         "y": 878,
         "x": 563
        }
       ]
      },
      {
       "key": "pok_merchant_crate",
       "title": "Merchant’s Crate of Supplies → 60 pp",
       "who": "solo",
       "detail": "Trep gives you a crate for a purification tablet (Freeport), keg of beer (Qeynos), ball of twine (Shadeweaver), bundle of weapons (Firiona), armor assortment (Thurgadin) and case of meat (Bazaar). Combine and hand back the Merchants Crate of Supplies.",
       "says": [
        {
         "to": "Trep Thilcan",
         "text": "ready to begin"
        }
       ],
       "where": [
        {
         "npc": "Trep Thilcan",
         "zone": "Plane of Knowledge",
         "y": -426,
         "x": 864
        }
       ]
      },
      {
       "key": "pok_instruments",
       "title": "Collection of Instruments → Fine Antique Amice",
       "who": "solo",
       "detail": "Minotaur Horn, Tambourine of Rituals, Stretched Skin Drum and Orcish Lute of Singing in a Collector’s Box; hand to Lohie Cantare.",
       "says": [
        {
         "to": "Curator Merri",
         "text": "collector's box"
        }
       ],
       "where": [
        {
         "npc": "Curator Merri",
         "zone": "Plane of Knowledge",
         "y": 865,
         "x": 668
        },
        {
         "npc": "Lohie Cantare",
         "zone": "Plane of Knowledge",
         "y": 820,
         "x": 640
        }
       ]
      },
      {
       "key": "pok_reflecting_pools",
       "title": "The Reflecting Pools of Tanaan → Fine Cut, Diamond Inlaid Mask + exp",
       "who": "solo",
       "detail": "Bring Sarnak Blood to Tarerd Gahar. His note goes to Vicar Thiran, whose book goes to Jeren Manri in Droga; bring back what Jeren gives you to Tratlan Jowyr.",
       "says": [
        {
         "to": "Tarerd Gahar",
         "text": "from me"
        }
       ],
       "where": [
        {
         "npc": "Tarerd Gahar",
         "zone": "Plane of Knowledge",
         "y": 675,
         "x": 407
        },
        {
         "npc": "Vicar Thiran",
         "zone": "Plane of Knowledge",
         "y": 8,
         "x": 1104
        },
        {
         "npc": "Jeren Manri",
         "zone": "Droga",
         "y": 472,
         "x": 1745
        },
        {
         "npc": "Tratlan Jowyr",
         "zone": "Plane of Knowledge",
         "y": 867,
         "x": 796
        }
       ]
      },
      {
       "key": "pok_sage_research",
       "title": "Sage research → a clicky and exp per turn-in",
       "who": "group",
       "detail": "Sage Balic starts you on a Sage’s Box of Research. Combine a Rune with its matching Words (classic research drops) and turn the Words in.",
       "says": [
        {
         "to": "Sage Balic",
         "text": "continue"
        },
        {
         "to": "Sage Balic",
         "text": "their research"
        }
       ],
       "where": [
        {
         "npc": "Sage Balic",
         "zone": "Plane of Knowledge",
         "y": -24,
         "x": 56
        }
       ]
      },
      {
       "key": "pok_books",
       "title": "Collection of Books → Fine Antique Locket",
       "who": "group",
       "detail": "Black Tome, Tome of the Eternal, Codex of the Warrior and the rare Book of Inspiration in a Collector’s Box; hand to Alexis Dubbani.",
       "where": [
        {
         "npc": "Alexis Dubbani",
         "zone": "Plane of Knowledge",
         "y": 908,
         "x": 640
        }
       ]
      },
      {
       "key": "pok_gems",
       "title": "Collection of Gems → Fine Antique Veil",
       "who": "group",
       "detail": "Blackened Sapphire, Greenscale Emerald, Shimmering Velium Ruby and the rare Hope Diamond in a Collector’s Box; hand to Drelynn Beaufax.",
       "where": [
        {
         "npc": "Drelynn Beaufax",
         "zone": "Plane of Knowledge",
         "y": 847,
         "x": 563
        }
       ]
      },
      {
       "key": "pok_idols",
       "title": "Collection of Idols → Fine Antique Velvet Rose",
       "who": "group",
       "detail": "Forlorn Totem of Rolfron Zek, Idol of Woven Grass, Coldain Fetish and the rare Petrified Totem in a Collector’s Box; hand back to Curator Merri.",
       "says": [
        {
         "to": "Curator Merri",
         "text": "special items"
        }
       ],
       "where": [
        {
         "npc": "Curator Merri",
         "zone": "Plane of Knowledge",
         "y": 865,
         "x": 668
        }
       ]
      }
     ]
    },
    {
     "key": "spells",
     "title": "Your PoP spells",
     "blurb": "Casters: this is where most of your power in PoP comes from.",
     "quests": [
      {
       "key": "spells_submit_book",
       "title": "Submit your spellbook on the PoP page",
       "who": "solo",
       "must": true,
       "detail": "Then the PoP page shows exactly which spells you still need, per parchment."
      },
      {
       "key": "spells_parchments",
       "title": "Collect Ethereal Parchment, Spectral Parchment and Glyphed Rune Word",
       "who": "group",
       "must": true,
       "detail": "They drop in the planes and now stack to 20."
      },
      {
       "key": "spells_turn_in",
       "title": "Turn them in to your class trainer in PoK",
       "who": "solo",
       "must": true,
       "detail": "One at a time; each gives a random spell from that parchment’s list for your class."
      }
     ]
    }
   ]
  },
  {
   "key": "t1",
   "title": "Tier One",
   "sub": "Justice · Innovation · Disease · Nightmare",
   "color": "#8b949e",
   "sections": [
    {
     "key": "t1",
     "title": "Tier one: the four open planes",
     "blurb": "Every plane here opens at 46. Talk to the NPC BEFORE each boss, or the kill will not flag you.",
     "quests": [
      {
       "key": "t1_trash",
       "title": "Level and farm in the tier-one planes",
       "who": "group",
       "detail": "Justice, Innovation, Disease and Nightmare trash is group content from 46."
      },
      {
       "key": "disease_ward",
       "title": "Disease, before Grummus: ask Adler Fuirstel about the ward",
       "who": "solo",
       "must": true,
       "says": [
        {
         "to": "Adler Fuirstel",
         "text": "what ward"
        }
       ],
       "where": [
        {
         "npc": "Adler Fuirstel",
         "zone": "Plane of Tranquility",
         "y": 1786,
         "x": -1467,
         "note": "outside the Plane of Disease portal"
        }
       ]
      },
      {
       "key": "flag_grummus",
       "title": "Kill Grummus (Plane of Disease)",
       "who": "group",
       "must": true,
       "detail": "Then hail A Planar Projection before anyone leaves. Then jump into the pit to reach the Crypt of Decay."
      },
      {
       "key": "justice_mavuin_info",
       "title": "Justice, before the trial: ask Mavuin for his information",
       "who": "solo",
       "must": true,
       "says": [
        {
         "to": "Mavuin",
         "text": "information"
        }
       ],
       "where": [
        {
         "npc": "Mavuin",
         "zone": "Plane of Justice",
         "y": -455,
         "x": 742
        }
       ],
       "expect": "Solo, a minute. He tells his story; “information” is the word that counts.",
       "back": [
        {
         "npc": "The Tribunal",
         "zone": "Plane of Justice",
         "y": 765,
         "x": 469,
         "note": "any of the six around the trial room"
        }
       ]
      },
      {
       "key": "flag_trial_justice",
       "title": "Win a Justice trial and loot its Mark",
       "who": "raid",
       "must": true,
       "detail": "Any one of the six: Mark of Execution, Mark of Flame, Mark of Lashing, Mark of Stone, Mark of Suffocation or Mark of Torture. The trial’s boss drops SIX of its Mark, one each, so one win covers six people; run it again for the rest. To start, tell that trial’s Tribunal “prove”, then “prepared”, then “I am ready to begin the Trial of Lashing” (or Execution, Stoning, Torture, Hanging, Flame); it takes everyone in your group standing close. After a win it can run again in 10 minutes, after a loss in 1.",
       "says": [
        {
         "to": "The Tribunal (at the trial)",
         "text": "prove"
        },
        {
         "to": "The Tribunal (at the trial)",
         "text": "prepared"
        }
       ],
       "expect": "A raid. Six Marks drop per win, one each, so bring six who need it and run it again for the rest. Pick any of the six trials. A loss can be retried in a minute, a win in ten.",
       "back": [
        {
         "npc": "The Tribunal",
         "zone": "Plane of Justice",
         "y": 765,
         "x": 469,
         "note": "any of the six around the trial room"
        }
       ]
      },
      {
       "key": "justice_tribunal",
       "title": "With your Mark in your bags, tell a Tribunal “mavuin sent me”",
       "who": "solo",
       "must": true,
       "detail": "Needs Mavuin’s “information” first. The Tribunal checks that you carry a Mark but does not take it; without one it says “You must prove yourself in one of our trials”. Keep the Mark.",
       "says": [
        {
         "to": "The Tribunal",
         "text": "mavuin sent me"
        }
       ],
       "where": [
        {
         "npc": "The Tribunal",
         "zone": "Plane of Justice",
         "y": 765,
         "x": 469,
         "note": "any of the six around the trial room"
        }
       ],
       "expect": "Solo, seconds. The Tribunal looks for a Mark in your bags. You keep it, so hold on to it for the Seventh Hammer.",
       "back": [
        {
         "npc": "Mavuin",
         "zone": "Plane of Justice",
         "y": -455,
         "x": 742
        }
       ]
      },
      {
       "key": "justice_mavuin_hail",
       "title": "Go back and hail Mavuin: that is your Justice flag",
       "who": "solo",
       "must": true,
       "detail": "The Bastion of Thunder shrine in the Plane of Storms checks for this flag, so do not skip it.",
       "where": [
        {
         "npc": "Mavuin",
         "zone": "Plane of Justice",
         "y": -455,
         "x": 742
        }
       ],
       "expect": "Solo, seconds. This hail is the Justice flag, and the Storms shrine checks it before it lets you into the Bastion of Thunder."
      },
      {
       "key": "justice_seventh_hammer",
       "title": "Optional: The Seventh Hammer (all six Marks)",
       "who": "raid",
       "detail": "With all six Marks in your bags, tell a Tribunal “knowledge” for The Mark of Justice; the Marks are checked, not taken. With only some it says there are more trials yet. Hold The Mark of Justice on your cursor and click a trial portal to reach the Hammer. Per person, and not needed for any flag.",
       "says": [
        {
         "to": "The Tribunal",
         "text": "knowledge"
        }
       ],
       "where": [
        {
         "npc": "The Tribunal",
         "zone": "Plane of Justice",
         "y": 765,
         "x": 469,
         "note": "any of the six around the trial room"
        }
       ],
       "expect": "A raid, later. Needs all six Marks on one person, so six trial wins. Not needed for any flag."
      },
      {
       "key": "innovation_door_key",
       "title": "Optional: the factory door key from Xanamech Nezmirthafen",
       "who": "raid",
       "detail": "One person in the raid needs it."
      },
      {
       "key": "innovation_test",
       "title": "Innovation, before the Behemoth: tell Giwin Mirakon you will test the machine",
       "who": "solo",
       "must": true,
       "says": [
        {
         "to": "Giwin Mirakon",
         "text": "I will test the machine"
        }
       ],
       "where": [
        {
         "npc": "Giwin Mirakon",
         "zone": "Plane of Innovation",
         "y": -52,
         "x": 49,
         "note": "inside the factory door"
        }
       ]
      },
      {
       "key": "flag_behemoth",
       "title": "Kill the Manaetic Behemoth, then hail Giwin Mirakon",
       "who": "raid",
       "must": true,
       "detail": "He appears near the boss room after the kill. The Behemoth wakes when the 10th clockwork device dies.",
       "expect": "A raid. The Behemoth wakes when the 10th clockwork device dies. Giwin Mirakon appears near the boss room afterwards.",
       "back": [
        {
         "npc": "Giwin Mirakon",
         "zone": "Plane of Innovation",
         "y": -52,
         "x": 49,
         "note": "inside the factory door"
        }
       ]
      },
      {
       "key": "nightmare_adroha",
       "title": "Nightmare, before the maze: talk to Adroha Jezith",
       "who": "solo",
       "must": true,
       "says": [
        {
         "to": "Adroha Jezith",
         "text": "Hail"
        },
        {
         "to": "Adroha Jezith",
         "text": "tortured by nightmares"
        }
       ],
       "where": [
        {
         "npc": "Adroha Jezith",
         "zone": "Plane of Tranquility",
         "y": -258,
         "x": -1428,
         "note": "sick bay"
        }
       ]
      },
      {
       "key": "flag_hedge",
       "title": "Thelin’s hedge maze (Plane of Nightmare), then hail Thelin Poxbourne",
       "who": "group",
       "must": true,
       "detail": "Up to 24 players, 4 groups per dream. Hail Thelin at the end to zone out. Opens the Lair of Terris Thule."
      },
      {
       "key": "essences_escort",
       "title": "Optional: escort Aid Eino through Nightmare for the Tiny Gold Fist (Essences of Power, part 1)",
       "who": "group",
       "detail": "The start phrase works only at night in game (8 PM to 7 AM). Stand by the big tree near the waterfall on the upper plateau and say “Quellious be my guide”. Aid Eino steps out and walks the zone while four waves come for him: 4 tortured banshees; 2 nightstalkers; 5 hobgoblins; then 4 banshees and 4 bats. He sits for a few minutes, then The Dreamkeeper appears (level 64, 40,000 HP, hits up to 622, slowable). Keep everything off Eino: he is level 50 with 10,000 HP. Loot the Strand of Nightmare, follow him to the Tranquility portal, and when he says “Hand me the strand from the beast”, give it to him for the Fist and 100,000 experience. One strand drops and he leaves after the hand-in, so it is one Fist per run. The tree answers again 36 minutes after a start. Keep the Fist: part two needs it. Hailing Aid Eino in PoK first is optional; “help” is where he tells you all this.",
       "says": [
        {
         "to": "The big tree in Nightmare",
         "text": "Quellious be my guide"
        },
        {
         "to": "Aid Eino (PoK, optional)",
         "text": "help"
        }
       ],
       "where": [
        {
         "npc": "The big tree by the waterfall",
         "zone": "Plane of Nightmare",
         "y": -510,
         "x": 1687,
         "note": "upper plateau; say it right beside the tree"
        },
        {
         "npc": "Aid Eino",
         "zone": "Plane of Knowledge",
         "y": -11,
         "x": 1005,
         "note": "top of the library elevator"
        }
       ],
       "expect": "A group or two. The waves come at points along his walk, with a rest between each. He waits 30 minutes for the strand at the portal, then leaves, and only one person gets the Fist per run, so plan a run each.",
       "back": [
        {
         "npc": "Councilwoman Kerasha",
         "zone": "Plane of Knowledge",
         "y": 0,
         "x": 1003,
         "note": "top of the library elevator"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "key": "t2",
   "title": "Tier Two",
   "sub": "Storms · Valor · Decay · T. Thule · Torment",
   "color": "#58a6ff",
   "sections": [
    {
     "key": "t2",
     "title": "Tier two",
     "blurb": "Each needs its tier-one flag. Zone into the next plane from the one you just finished.",
     "quests": [
      {
       "key": "flag_tthule",
       "title": "Kill Terris Thule (Lair of Terris Thule)",
       "who": "raid",
       "must": true,
       "detail": "Then hail A Planar Projection before anyone leaves.",
       "back": [
        {
         "npc": "Elder Poxbourne",
         "zone": "Plane of Tranquility",
         "y": -251,
         "x": -1426,
         "note": "sick bay"
        }
       ]
      },
      {
       "key": "nightmare_poxbourne",
       "title": "Hail Elder Poxbourne in Tranquility",
       "who": "solo",
       "must": true,
       "where": [
        {
         "npc": "Elder Poxbourne",
         "zone": "Plane of Tranquility",
         "y": -251,
         "x": -1426,
         "note": "sick bay"
        }
       ]
      },
      {
       "key": "cod_fuirstel_before",
       "title": "Crypt of Decay, first: hail Elder Fuirstel",
       "who": "solo",
       "must": true,
       "detail": "Only answers once your Grummus flag is done.",
       "where": [
        {
         "npc": "Elder Fuirstel",
         "zone": "Plane of Tranquility",
         "y": -291,
         "x": -1417,
         "note": "sick bay"
        }
       ]
      },
      {
       "key": "flag_carprin",
       "title": "The Carprin event, then hail Tarkil Adan",
       "who": "group",
       "check": true,
       "detail": "Five nameds. Tarkil puts the key to the lower Crypt on your keyring."
      },
      {
       "key": "flag_bert",
       "title": "Kill Bertoxxulous",
       "who": "raid",
       "must": true,
       "detail": "Then hail A Planar Projection before anyone leaves.",
       "back": [
        {
         "npc": "Elder Fuirstel",
         "zone": "Plane of Tranquility",
         "y": -291,
         "x": -1417,
         "note": "sick bay"
        }
       ]
      },
      {
       "key": "cod_fuirstel_after",
       "title": "Hail Elder Fuirstel again",
       "who": "solo",
       "must": true,
       "where": [
        {
         "npc": "Elder Fuirstel",
         "zone": "Plane of Tranquility",
         "y": -291,
         "x": -1417,
         "note": "sick bay"
        }
       ]
      },
      {
       "key": "flag_askr",
       "title": "Askr the Lost: one head, one bag, one meld (Plane of Storms)",
       "who": "group",
       "must": true,
       "detail": "Everyone does their own. 1) Hand Askr ONE Storm Giant Head (any camp’s; 60% from its giants). Then say “it was me”, “paying attention”, and “continue” twice for Askr’s Bag of Verity. 2) Combine a Storm Volaas Beard (south camp), a Storm Taarid Bone (west) and a Storm Satuur Sash (north) in the bag; give him Askr’s Sealed Bag of Verity. 3) Say “bastion of thunder” for a second bag; combine two Esoteric Medallions from DIFFERENT camps in it (south, west or north; each camp’s named drops three) and give him the Esoteric Meld. Leaving the zone resets his conversation, so answer him right after each hand-in.",
       "says": [
        {
         "to": "Askr the Lost",
         "text": "it was me"
        },
        {
         "to": "Askr the Lost",
         "text": "paying attention"
        },
        {
         "to": "Askr the Lost",
         "text": "continue"
        },
        {
         "to": "Askr the Lost",
         "text": "bastion of thunder"
        }
       ],
       "where": [
        {
         "npc": "Askr the Lost",
         "zone": "Plane of Storms",
         "y": -1255,
         "x": -2576
        }
       ],
       "expect": "A group clears a camp at a time. Everyone needs their own head, their own three parts and two medallions from different camps, and each camp’s named drops three medallions. Stay in the zone until you are done with him: leaving resets the conversation.",
       "turnIn": [
        {
         "to": {
          "npc": "Askr the Lost",
          "zone": "Plane of Storms",
          "y": -1255,
          "x": -2576
         },
         "give": "one Storm Giant Head (any camp’s)",
         "get": "Askr’s Bag of Verity after “it was me”, “paying attention”, “continue”, “continue”"
        },
        {
         "to": {
          "npc": "Askr the Lost",
          "zone": "Plane of Storms",
          "y": -1255,
          "x": -2576
         },
         "give": "Askr’s Sealed Bag of Verity (beard + bone + sash combined in the bag)",
         "get": "the first flag; say “bastion of thunder” for a second bag"
        },
        {
         "to": {
          "npc": "Askr the Lost",
          "zone": "Plane of Storms",
          "y": -1255,
          "x": -2576
         },
         "give": "Esoteric Meld (two medallions from different camps, combined)",
         "get": "the Askr flag"
        }
       ],
       "back": [
        {
         "npc": "The shrine in Mount Grenidor",
         "zone": "Plane of Storms",
         "y": -163,
         "x": -362,
         "note": "the stone in the middle of Storms"
        }
       ]
      },
      {
       "key": "storms_zone_bot",
       "title": "Click the shrine in Mount Grenidor to enter the Bastion of Thunder",
       "who": "solo",
       "must": true,
       "detail": "Needs Askr’s flag AND your Justice flag (the last Mavuin hail). The “Talisman of Thunderous Foyer” is this click, a flag, not a keyring item. Without both flags the shrine says it finds no mystic symbol. You land in the lower halls.",
       "where": [
        {
         "npc": "The shrine in Mount Grenidor",
         "zone": "Plane of Storms",
         "y": -163,
         "x": -362,
         "note": "the stone in the middle of Storms"
        }
       ],
       "expect": "Solo. With both flags the shrine sends you to the lower halls of the Bastion of Thunder. Without the Justice flag it finds “no mystic symbol”: go back to Mavuin."
      },
      {
       "key": "valor_globe",
       "title": "Optional: A Crystalline Globe for Aerin`Dar’s door",
       "who": "group",
       "detail": "At least one person needs it. The patch doubled the globe-piece drops."
      },
      {
       "key": "flag_aerindar",
       "title": "Kill Aerin`Dar (Plane of Valor)",
       "who": "raid",
       "must": true,
       "detail": "Then hail A Planar Projection before anyone leaves."
      },
      {
       "key": "valor_zone_hoh",
       "title": "Zone into the Halls of Honor by the Valor underground tunnel",
       "who": "solo",
       "must": true
      },
      {
       "key": "torment_fahlia",
       "title": "Torment, first: tell Fahlia Shadyglade you will go",
       "who": "solo",
       "must": true,
       "detail": "Needs the Disease, Crypt and Nightmare flags done in order.",
       "says": [
        {
         "to": "Fahlia Shadyglade",
         "text": "i will go"
        }
       ],
       "where": [
        {
         "npc": "Fahlia Shadyglade",
         "zone": "Plane of Tranquility",
         "y": -301,
         "x": -1365,
         "note": "sick bay"
        }
       ]
      },
      {
       "key": "torment_sphere",
       "title": "Optional: A Screaming Sphere for Saryrn’s tower door",
       "who": "raid",
       "detail": "One person needs it. An Unimaginable Horror now respawns in 30 minutes."
      },
      {
       "key": "flag_keeper",
       "title": "The Keeper of Sorrows, then hail Tylis Newleaf",
       "who": "raid",
       "detail": "A small raid; resets every 2 hours. Whoever asks for it must be flagged this far.",
       "back": [
        {
         "npc": "Tylis Newleaf",
         "zone": "Plane of Tranquility",
         "y": -294,
         "x": -1371,
         "note": "sick bay"
        }
       ]
      },
      {
       "key": "flag_saryrn",
       "title": "Kill Saryrn",
       "who": "raid",
       "must": true,
       "detail": "Then hail A Planar Projection before anyone leaves.",
       "back": [
        {
         "npc": "Fahlia Shadyglade",
         "zone": "Plane of Tranquility",
         "y": -301,
         "x": -1365,
         "note": "sick bay"
        },
        {
         "npc": "Tylis Newleaf",
         "zone": "Plane of Tranquility",
         "y": -294,
         "x": -1371,
         "note": "sick bay"
        }
       ]
      },
      {
       "key": "torment_return",
       "title": "Hail Fahlia Shadyglade and Tylis Newleaf in the sick bay, then Maelin",
       "who": "solo",
       "where": [
        {
         "npc": "Fahlia Shadyglade",
         "zone": "Plane of Tranquility",
         "y": -301,
         "x": -1365,
         "note": "sick bay"
        },
        {
         "npc": "Tylis Newleaf",
         "zone": "Plane of Tranquility",
         "y": -294,
         "x": -1371,
         "note": "sick bay"
        },
        {
         "npc": "Grand Librarian Maelin",
         "zone": "Plane of Knowledge",
         "y": 6,
         "x": 1016,
         "note": "top of the library elevator"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "key": "t3",
   "title": "Tier Three",
   "sub": "Thunder · Honor · Tactics · Sol Ro",
   "color": "#d29922",
   "sections": [
    {
     "key": "t3",
     "title": "Tier three",
     "blurb": "The gods’ champions. All raids.",
     "quests": [
      {
       "key": "bot_symbol",
       "title": "The Symbol of Torden opens Agnarr’s tower: one per raid, and the raid needs it",
       "who": "raid",
       "detail": "Combine the Sandstorm Sphere, Lightning Sphere, Blizzard Sphere and Tornado Sphere inside an Unadorned Symbol of Torden. Each sphere is a 25% drop from wing trash; the Unadorned Symbol drops from Auliffe Chaoswind, Brynju Thunderclap, Eindride Icestorm, Kuanbyr Hailstorm or Agnarr’s four adds. The holder puts it on the cursor and clicks the courtyard tower portal; the raid then has 5 minutes to click in. Anyone else clicking wakes the storm watchers.",
       "where": [
        {
         "npc": "The tower portal",
         "zone": "Bastion of Thunder",
         "y": 11,
         "x": 170,
         "note": "in the courtyard"
        }
       ],
       "expect": "The raid farms the four spheres and one Unadorned Symbol. One raider carries the finished Symbol; everyone else clicks the portal within 5 minutes of them.",
       "turnIn": [
        {
         "to": {
          "npc": "The tower portal",
          "zone": "Bastion of Thunder",
          "y": 11,
          "x": 170,
          "note": "in the courtyard"
         },
         "give": "the Symbol of Torden on your cursor, then click",
         "get": "5 minutes for your raid to follow you in"
        }
       ]
      },
      {
       "key": "bot_tower",
       "title": "In the tower: Evynd Firestorm, then Askr; Emmerik Skyfury, then Askr again",
       "who": "raid",
       "must": true,
       "detail": "Everyone does both. When Evynd Firestorm dies, hail Askr the Lost and say “transport”. When Emmerik Skyfury dies, hail him again and say “what storm”; he opens A Chaotic Vortex. Click it to reach Agnarr. Askr, the vortex and Karana leave after 55 minutes.",
       "says": [
        {
         "to": "Askr the Lost",
         "text": "transport"
        },
        {
         "to": "Askr the Lost",
         "text": "what storm"
        }
       ],
       "where": [
        {
         "npc": "Askr the Lost",
         "zone": "Bastion of Thunder",
         "y": -1732,
         "x": -1123,
         "note": "appears when Evynd Firestorm dies"
        },
        {
         "npc": "Askr the Lost",
         "zone": "Bastion of Thunder",
         "y": -1733,
         "x": -1065,
         "note": "appears when Emmerik Skyfury dies"
        }
       ],
       "expect": "A raid. Everyone talks to Askr twice, once after each tower boss. Askr, the vortex and Karana stay 55 minutes.",
       "back": [
        {
         "npc": "Karana",
         "zone": "Bastion of Thunder",
         "y": -1758,
         "x": -477,
         "note": "appears when Agnarr dies"
        }
       ]
      },
      {
       "key": "flag_agnarr",
       "title": "Kill Agnarr the Storm Lord, then speak to Karana",
       "who": "raid",
       "must": true,
       "detail": "Karana answers only the raid that got the kill, up to 72 people. “Follow the path of the Fallen” gives the real flag only if you came into the Bastion through the Storms shrine. “Send me on my path” casts Gate: you land at your bind point.",
       "says": [
        {
         "to": "Karana",
         "text": "I will follow the path of the Fallen."
        },
        {
         "to": "Karana",
         "text": "Send me on my path."
        }
       ],
       "where": [
        {
         "npc": "Karana",
         "zone": "Bastion of Thunder",
         "y": -1758,
         "x": -477,
         "note": "appears when Agnarr dies"
        }
       ],
       "expect": "A raid. Karana answers up to 72 people from the raid with the kill. Ask for the path of the Fallen before “send me”, which casts Gate."
      },
      {
       "key": "hoh_trial_dragon",
       "title": "Halls of Honor trial 1 (the dragon), then hail Trydan Faye",
       "who": "raid",
       "must": true,
       "where": [
        {
         "npc": "Trydan Faye",
         "zone": "Halls of Honor",
         "y": 2040,
         "x": -1725,
         "note": "northeast trial"
        }
       ]
      },
      {
       "key": "hoh_trial_villagers",
       "title": "Trial 2 (save the villagers), then hail Rhaliq Trell",
       "who": "raid",
       "must": true,
       "where": [
        {
         "npc": "Rhaliq Trell",
         "zone": "Halls of Honor",
         "y": 1374,
         "x": 456,
         "note": "northwest trial"
        }
       ]
      },
      {
       "key": "hoh_trial_villager",
       "title": "Trial 3 (save one villager), then hail Alekson Garn",
       "who": "raid",
       "must": true,
       "detail": "A failed trial can be retried after 10 minutes.",
       "where": [
        {
         "npc": "Alekson Garn",
         "zone": "Halls of Honor",
         "y": -1724,
         "x": -2330,
         "note": "southeast trial"
        }
       ]
      },
      {
       "key": "flag_marr",
       "title": "Kill Mithaniel Marr (Temple of Marr)",
       "who": "raid",
       "must": true,
       "detail": "Then hail A Planar Projection before anyone leaves."
      },
      {
       "key": "tactics_maelin_before",
       "title": "Before the Zeks: visit Grand Librarian Maelin",
       "who": "solo",
       "must": true,
       "says": [
        {
         "to": "Grand Librarian Maelin",
         "text": "Hail"
        },
        {
         "to": "Grand Librarian Maelin",
         "text": "what lore"
        },
        {
         "to": "Grand Librarian Maelin",
         "text": "what information"
        }
       ],
       "where": [
        {
         "npc": "Grand Librarian Maelin",
         "zone": "Plane of Knowledge",
         "y": 6,
         "x": 1016,
         "note": "top of the library elevator"
        }
       ]
      },
      {
       "key": "flag_vallon",
       "title": "Kill Vallon Zek",
       "who": "raid",
       "detail": "Then hail A Planar Projection before anyone leaves."
      },
      {
       "key": "flag_tallon",
       "title": "Kill Tallon Zek",
       "who": "raid",
       "detail": "Then hail A Planar Projection before anyone leaves."
      },
      {
       "key": "flag_rallos",
       "title": "Kill Rallos Zek",
       "who": "raid",
       "must": true,
       "detail": "Then hail A Planar Projection before anyone leaves."
      },
      {
       "key": "tactics_maelin_after",
       "title": "After the Zeks: Maelin again, then the Seer",
       "who": "solo",
       "must": true,
       "says": [
        {
         "to": "Grand Librarian Maelin",
         "text": "what information"
        },
        {
         "to": "Seer Mal Nae`Shi",
         "text": "unlock my memories",
         "sit": true
        }
       ],
       "where": [
        {
         "npc": "Grand Librarian Maelin",
         "zone": "Plane of Knowledge",
         "y": 6,
         "x": 1016,
         "note": "top of the library elevator"
        },
        {
         "npc": "Seer Mal Nae`Shi",
         "zone": "Plane of Knowledge",
         "y": -42,
         "x": -224,
         "note": "next to the Plane of Tranquility book"
        }
       ]
      },
      {
       "key": "flag_solro_minis",
       "title": "The five Tower of Solusek Ro minis",
       "who": "raid",
       "detail": "Jiva, Xuzl, Arlyxir, Rizlona and the Protector of Dresolik; click through the stone after each one. Solusek Ro’s chamber also needs every flag up to Rallos Zek."
      },
      {
       "key": "flag_solro",
       "title": "Kill Solusek Ro",
       "who": "raid",
       "must": true,
       "detail": "Then hail A Planar Projection before anyone leaves. Then drop into the lava pit in his chamber to reach the Plane of Fire."
      }
     ]
    }
   ]
  },
  {
   "key": "t4",
   "title": "Tier Four — Elemental",
   "sub": "Earth · Air · Water · Fire",
   "color": "#f0883e",
   "sections": [
    {
     "key": "t4",
     "title": "The elemental planes",
     "blurb": "Need Marr, Agnarr, Saryrn, Rallos Zek and Bertoxxulous. Fire also needs Solusek Ro. Can’t zone in with every flag done? Go back and forth between Grand Librarian Maelin and the Seer until neither has more for you.",
     "quests": [
      {
       "key": "flag_fennin",
       "title": "Kill Fennin Ro (Plane of Fire)",
       "who": "raid",
       "must": true,
       "detail": "Hail A Planar Projection to receive the Globe of Dancing Flame."
      },
      {
       "key": "air_key",
       "title": "Optional: A Wind Etched Key to reach Xegony’s island",
       "who": "raid",
       "detail": "One per group. Once the holder clicks the rainbow, the group has 5 minutes to follow."
      },
      {
       "key": "flag_avatars_air",
       "title": "Kill the four air avatars",
       "who": "raid",
       "check": true
      },
      {
       "key": "flag_xegony",
       "title": "Kill Xegony (Plane of Air)",
       "who": "raid",
       "must": true,
       "detail": "Hail A Planar Projection to receive the Amorphous Cloud of Air."
      },
      {
       "key": "flag_coirnav",
       "title": "Kill Coirnav (Plane of Water)",
       "who": "raid",
       "must": true,
       "detail": "Hail A Planar Projection to receive the Sphere of Coalesced Water."
      },
      {
       "key": "earth_key",
       "title": "Optional: A Gem-Etched Key from Tantisala Jaggedtooth",
       "who": "raid",
       "detail": "One person needs it to open the door to the tunnels in Plane of Earth A."
      },
      {
       "key": "flag_arbitor",
       "title": "The four earth rings and A Mystical Arbitor of Earth",
       "who": "raid",
       "must": true,
       "check": true,
       "detail": "Hail A Planar Projection for the Passkey of the Twelve, then click the door into Plane of Earth B."
      },
      {
       "key": "flag_rathe",
       "title": "Kill the Rathe Council (the Avatar of Earth)",
       "who": "raid",
       "must": true,
       "detail": "Hail A Planar Projection to receive the Mound of Living Stone."
      },
      {
       "key": "essences_power",
       "title": "Optional: the four Essences of Power for a Jade Hoop of Speed or another reward (part 2)",
       "who": "raid",
       "detail": "Carry the Tiny Gold Fist: Councilwoman Kerasha answers only while you have it, and checks no flags. Say “essences of power” for a Sacred Bowl. Put in the Essence of Fire (Fennin Ro), Essence of Wind (Xegony), Essence of Water (Coirnav) and Essence of Earth (the Avatar of Earth, the Rathe Council), and combine for Power of the Planes. Each god drops its essence on 40% of kills, one per kill, and you can hold only one of each, so they are a loot call. They are not the four the Plane of Time needs. Give her Power of the Planes for the Jade Hoop of Speed. To change it, hand the reward back for the next one, in this order: Frizzniks Endless Coin Purse, Cord of Invigoration, Mace of the Ancients, Ring of Farsight, then the Hoop again.",
       "says": [
        {
         "to": "Councilwoman Kerasha",
         "text": "essences of power"
        }
       ],
       "where": [
        {
         "npc": "Councilwoman Kerasha",
         "zone": "Plane of Knowledge",
         "y": 0,
         "x": 1003,
         "note": "top of the library elevator"
        }
       ],
       "expect": "Solo once you hold all four essences. Getting them is four raid kills at 40% each, so the guild decides who they go to.",
       "turnIn": [
        {
         "to": {
          "npc": "Councilwoman Kerasha",
          "zone": "Plane of Knowledge",
          "y": 0,
          "x": 1003,
          "note": "top of the library elevator"
         },
         "give": "Power of the Planes (the four essences combined in the bowl)",
         "get": "Jade Hoop of Speed"
        },
        {
         "to": {
          "npc": "Councilwoman Kerasha",
          "zone": "Plane of Knowledge",
          "y": 0,
          "x": 1003,
          "note": "top of the library elevator"
         },
         "give": "the reward you hold",
         "get": "the next one: Coin Purse, Cord, Mace, Ring, then the Hoop again"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "key": "time",
   "title": "Plane of Time",
   "sub": "Time",
   "color": "#a371f7",
   "sections": [
    {
     "key": "time",
     "title": "The Plane of Time",
     "blurb": "Needs all four elemental gods and their four essences.",
     "quests": [
      {
       "key": "time_vial",
       "title": "Optional: craft an Odylic Vial",
       "who": "solo",
       "detail": "A tradable four-slot pottery container; one per raid is enough."
      },
      {
       "key": "time_quintessence",
       "title": "Combine the four essences into the Quintessence of Elements",
       "who": "solo",
       "must": true,
       "detail": "In the Odylic Vial: the Globe of Dancing Flame, Amorphous Cloud of Air, Sphere of Coalesced Water and Mound of Living Stone."
      },
      {
       "key": "time_muon",
       "title": "Enter the Plane of Time from Innovation",
       "who": "solo",
       "must": true,
       "detail": "Carry the Quintessence to Chronographer Muon, go up to the clocks, tell Loreseeker Maelin you have researched, then click the machine.",
       "says": [
        {
         "to": "Chronographer Muon",
         "text": "yes"
        },
        {
         "to": "Loreseeker Maelin",
         "text": "researched"
        }
       ],
       "where": [
        {
         "npc": "Chronographer Muon",
         "zone": "Plane of Innovation",
         "y": 34,
         "x": -310
        }
       ]
      },
      {
       "key": "time_timelockout",
       "title": "Type #timelockout",
       "who": "solo",
       "detail": "Shows your guild’s timeline, when it retires, and which encounters are open in each phase."
      },
      {
       "key": "flag_quarm",
       "title": "Kill Quarm",
       "who": "raid",
       "must": true
      }
     ]
    }
   ]
  }
 ]
};
